### PR TITLE
Add puppeteer

### PR DESCRIPTION
**Pull request by karlsnyder0**
Add headless browser support and test suite Promise chains.

### CODE REVIEW

**Comment by jasonbyrne** [comment]
Two things:

1) Why do we need Bluebird? I would rather limit additional dependencies if possible. There is a native Promise object. What do we gain?

2) The normal format for setting the type of the scenario is with a method like .json() or .html() etc... so I would rather not break convention with that for the browser to be a second argument when instantiating Scenario. Why not make it like .browser(browserOptions) instead? 

3) Does adding the puppeteer as a dependency make the size of the package a lot bigger? I remember you mentioning something about core vs the browser itself?

**Comment by karlsnyder0** [comment]
> Two things:
> 
> 1. Why do we need Bluebird? I would rather limit additional dependencies if possible. There is a native Promise object. What do we gain?

I know we discussed this last night but I wanted to put this in here as a reminder.  Bluebird gives us serial promise handling.  This is important because browsing can only work with one driver at the wheel.

> 2. The normal format for setting the type of the scenario is with a method like .json() or .html() etc... so I would rather not break convention with that for the browser to be a second argument when instantiating Scenario. Why not make it like .browser(browserOptions) instead?

I'll give this a shot.

> 3. Does adding the puppeteer as a dependency make the size of the package a lot bigger? I remember you mentioning something about core vs the browser itself?

I wanted to make sure you really cared about this one.  I'll create a dynamic loader that uses the puppeteer dependency if available and falls back to puppeteer-core.

**Comment by karlsnyder0** [comment]
@jasonbyrne This one is ready to go!

**Comment by jasonbyrne** [comment]
Cool. Thanks Karl!

**Pull request merged**
